[project]
name = "utl"
version = "0.1.0b1"
description = "A small Telegram Type Language implementation"
authors = [{ name = "RuslanUC", email = "dev_ruslan_uc@protonmail.com" }]
requires-python = ">=3.10,<4.0"
readme = "README.md"
license = "MIT"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: C",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development",
    "Typing :: Typed",
]

[project.urls]
homepage = "https://github.com/RuslanUC/utl"
repository = "https://github.com/RuslanUC/utl"

[dependency-groups]
dev = [
    "pytest>=8.3.3,<9",
    "cibuildwheel>=2.22.0,<3",
    "pyrogram>=2.0.106,<3",
    "py-spy>=0.4.2,<0.5",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = ["pyutl"]
module-root = ""
source-include = [
    "CMakeLists.txt",
    "ext/arena-allocator/CMakeLists.txt/**",
    "ext/arena-allocator/src/*.c",
    "ext/arena-allocator/include/*.h",
    "utl/CMakeLists.txt",
    "utl/src/*.c",
    "utl/include/*.h",
    "python/CMakeLists.txt",
    "python/src/*.c",
    "python/include/*.h",
]

[build-system]
requires = ["uv_build>=0.11.6,<0.12.0"]
build-backend = "uv_build"

[tool.cibuildwheel]
build = "{cp310,cp311,cp312,cp313,pp310}-{many,musl}linux_{x86_64,i686,aarch64,armv7l}"

[tool.cibuildwheel.linux]
archs = ["auto", "aarch64"]
