from io import BytesIO
from typing import Optional, Literal
from collections.abc import MutableSequence

class TLVector(MutableSequence):
    def append(self, item: object) -> None: ...


class TLType:
    ...


class TLObject:
    __tl_id__: int
    __layer__: int
    __section__: int
    __tl__: str | None

    def __init__(self, **kwargs) -> None: ...

    def __getattr__(self, item: str) -> object: ...

    def __setattr__(self, item: str, value: object) -> None: ...

    @classmethod
    def read(cls, buf: BytesIO, read_only: bool = False, /) -> TLObject: ...

    @classmethod
    def read_bytes(cls, buf: bytes, read_only: bool = False, /) -> TLObject: ...

    def write(self) -> bytes: ...


class __DefPool:
    def parse(self, tl_type_def: str, layer: int, section: Literal[0, 1], /) -> type[TLObject]: ...

    def has_type(self, tl_type: str, /) -> bool: ...

    def get_type(self, tl_type: str, /) -> type[TLType]: ...

    def create_type(self, tl_type: str, /) -> type[TLType]: ...

    def has_constructor(self, tl_id: int, /) -> bool: ...

    def get_constructor(self, tl_id: int, /) -> Optional[type[TLObject]]: ...


def_pool: __DefPool

def parse_tl(tl_type_def: str, layer: int, section: Literal[0, 1], /) -> type[TLObject]: ...

def has_type(tl_type: str, /) -> bool: ...

def get_type(tl_type: str, /) -> type[TLType]: ...

def create_type(tl_type: str, /) -> type[TLType]: ...

def has_constructor(tl_id: int, /) -> bool: ...

def get_constructor(tl_id: int, /) -> Optional[type[TLObject]]: ...
